spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fs_scanner
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

application-settings:
  worker-threads-count: 10